### ISSUE TITLE
The game crashes when you deselect the current item

### ISSUE THREAD

**Issue by ghost** [deltanedas/item-grabber#1]
How to replicate:
-Load a game
-Open the item selection menu (right click on the copper)
-Select the current item

[crash-report-11_04_2021_15_31_57.txt](https://github.com/DeltaNedas/item-grabber/files/7475547/crash-report-11_04_2021_15_31_57.txt)

**Comment by deltanedas** [comment]
cant reproduce, but i dont know what "select the current item" means so i just played around with the button and carried item
